spring:
  application:
    name: notification-service

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2000
          max-attempts: 3
          multiplier: 2.0

# HTTP-порт для Spring Boot и WebSocket
server:
  port: 8084

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
